### ISSUE TITLE
Compile error missing action directory in segbot_arm_perception

### ISSUE THREAD

**Issue by nj1407** [utexas-bwi/segbot_arm#16]
The current code in master is missing the directory action under segbot_arm_perception and the file LogPerception.action in that directory causing CMake errors when compiling the code.This code can be found in previous commits or in my personal fork of master where I fixed the issue.

**Comment by maxsvetlik** [comment]
Jivko:
Can you fix it on a branch and do a pull request? If you think your
fork is way out of date, it may be easier to just tell me what the
solution is.

---

**Comment by maxsvetlik** [comment]
This may have been something I removed during the first round of clean up. I'll investigate this soon.
Nathan, if you have a fix on a fork you can do a PR.

**Comment by nj1407** [comment]
I made a PR you can look over it when you have time
