### ISSUE TITLE
Error with autonmous navigation with segbot_arm

### ISSUE THREAD

**Issue by nj1407** [utexas-bwi/segbot_arm#19]
After updating my workspaces in segbot_arm and wstool update the arm robot fails to autonomously navigate having the error 

[ERROR] [1470952622.452672195]: NO PATH!
[ERROR] [1470952622.452903850]: Failed to get a plan from potential when a legal potential was found. This shouldn't happen.

This occurs when running both go_to_object_node and go_to_location in bwi_tasks and even when giving nav goals the robot moves a bit and then starts spinning in the recovery action even though it is localized correctly and the /mico_nav_safety service has been called and the arm is in the safety position.

**Comment by maxsvetlik** [comment]
Can you confirm that this is a conflict with segbot_arm and not a workspace problem? ie do the issues persist if you run the same tasks, but bring up the robot using the bwi_launch/segbot_v2.launch file?

**Comment by nj1407** [comment]
After I updated my workspace again this morning with the changes from the last  few weeks and issue got resolved, I don't know why.
