### ISSUE TITLE
Libfft3-dev [undefined reference to `fftw_plan_dft_r2c_1d']

### ISSUE THREAD

**Issue by maxsvetlik** [utexas-bwi/segbot_arm#3]
After following the steps in the segbot_arm readme, I'm still having trouble compiling packages that use libfft3 (specifically audio_logger)

To reproduce: Create a vanilla workspace on a vanilla machine (one that doesn't have the segbot_arm dependencies installed) and step through the readme

@PriyankaKhante

**Comment by maxsvetlik** [comment]
closed by 566f5ce

**Comment by jack-oquin** [comment]
I think we also need a depend in package.xml for libfftw3, which is [already defined in rosdep](https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L1243).
