### ISSUE TITLE
Migrating to Alienware GPU

### ISSUE THREAD

**Issue by vczhou** [utexas-bwi/segbot_arm#52]
Migrating to use the Alienware GPU. Ran into some issues when setting it up: 

When running 
```
roslaunch segbot_arm_launch segbot_v2.arm.launch
```
everything is fine except it can't open the kinect.
```
[ INFO] [1508518476.446176012]: Searching for device with index = 1
[ INFO] [1508518476.447196672]: No matching device found.... waiting for devices. Reason: [ERROR] Unable to open specified kinect
```
In addition, I can't run/ connect the arm. Running 
```
roslaunch kinova_bringup kinova_robot.launch kinova_robotType:=m1n6s200 
``` 
gives the following error: 
```
[ERROR] [1508518307.855257210]: KinovaCommException: Could not get general information about the device (return code: 1015)
```
On RVIZ, it's shown that there are no transforms from the arm except from m1n6s200_link_base.

**Comment by vczhou** [comment]
Arm issue is fixed by adding the udev rules by running
```
sudo cp kinova_driver/udev/10-kinova-arm.rules /etc/udev/rules.d/
```

**Comment by mayurir7** [comment]
For gpd tutorial 1, the following two lines of code were changed to make it work with the xtion:

- gpd/tutorials/openni2.rviz, line 110: change camera_link to xtion_camera_link
- gpd/launch/tutorial1.launch, line 20: change camera to xtion_camera

**Comment by nickswalker** [comment]
Running list of todos:
- [ ] Headless localization: we can't set an initial pose on the robot remotely right now because we won't have a monitor connected
- [ ] Silence empty jointstate messages. They don't seem to indicate any real issue (the joint state messages are all fine)
- [ ] Add microphone to URDF. Some arm trajectories get pretty close to whacking it.

**Comment by nickswalker** [comment]
I tried running the robot fully under its own power during some Kinetic testing tonight. The standard roslaunch (but with rviz disabled) causes a voltage sag and resets the platform. This is with the computer on one inverter and the arm and base on another.

This behavior (not the inverter faulting, but the platform as a whole blinking out) leads me to believe that we are exceeding the battery's maximum current draw. I am not familiar enough with this platform's power distribution board to measure this safely, but it should be possible to partially disassemble it to get an instrument in there.

Until this is resolved we cannot run the robot untethered.

**Comment by nickswalker** [comment]
I was able to launch successfully after throttling the CPU

    sudo cpufreq-set -g powersave --cpu 7 --max 800Mhz

**Comment by maxsvetlik** [comment]
The power distribution for this robot has been reworked to eliminate the voltage sagging issues described above. Throttling the computer is no longer necessary. 
Closing this for now, and splitting off a new issue for the URDF problems.
