### ISSUE TITLE
Xtion camera and Kinect conflict while running simultaneously 

### ISSUE THREAD

**Issue by maxsvetlik** [utexas-bwi/segbot_arm#7]
There seems to be some conflict between the Kinect (launched with freenect) and the Xtion Pro (using openni2 launch). Namely, with both running, openni2 hangs up trying to find the Xtion, which prevents other usb events (like detecting the arm and starting its driver). This can be seen in RViz via the 'RobotModel' plugin, as it complains that there are no data from the arm links. This does not happen when only a single camera is connected.

To reproduce: launch segbot_v2.arm.launch with both the Kinect and Xtion connected.

I suspect this is the root of the "sometimes the arm is detected, sometimes it isn't" issue we've seen the last month

**Comment by piyushk** [comment]
You'll need to provide device serial ids for the xtion pro in the launch file, so that the driver doesn't try and open the Kinect.

**Comment by jsinapov** [comment]
Closed. I added device_id in the launch file for openni2.

**Comment by maxsvetlik** [comment]
This problem is ongoing, despite device IDs specified. Requires further investigation.
