### ISSUE TITLE
Missing include in grasp_utils.h

### ISSUE THREAD

**Issue by nj1407** [utexas-bwi/segbot_arm#8]
There is a missing include in segbot_arm/segbot_arm_manipulation/include/segbot_arm_manipulation/grasp_utils.h 
It's missing
 #include  tf_conversions/tf_eigen.h
 for tf matrixEigenToTF function.

**Comment by jack-oquin** [comment]
Nathan,

If you have a fix, go ahead and fork the repository, add the missing include, and submit a pull request.

Thanks!

**Comment by jsinapov** [comment]
Missing includes have now been added. Let me know if you still get any issues.
